#!/usr/bin/env python
import sys
import time


sys.stdout.write("\033[s")
global i
i = 0

try:
    while True:
        i = i % 12
        sys.stdout.write("\033[s")
        with open("escaped_images/" + str(i), 'r') as f:
            sys.stdout.write(f.read())
        # sys.stdout.write("\033[18A")
        sys.stdout.write("\033[u")
        time.sleep(0.06)
        i += 1
except KeyboardInterrupt:
    sys.stdout.write("\033[u")

